
    
aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &root-restore-yarn-cache
    keys:
      - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - root-yarn-{{ .Branch }}-

  - &root-save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &root-checkout
    path: ~/unmock-docs

  - &root-build
    name: Run build
    command: yarn build


defaults: &defaults
  working_directory: ~/unmock-docs/website
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout: *root-checkout
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run: *root-build
  deploy:
    <<: *defaults
    steps:
      - checkout: *root-checkout
      - run:
          name: Deploy master
          command: |
            echo "Not implemented"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #      - build
      #    filters:
      #      branches:
      #        only: master