
    
aliases:
  - &root-yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &root-restore-yarn-cache
    keys:
      - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - root-yarn-{{ .Branch }}-

  - &root-save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

defaults: &defaults
  working_directory: ~/unmock-docs/website
  docker:
    - image: circleci/node:8
  # resource_class: large

version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: *root-restore-yarn-cache
      - run: *root-yarn
      - save_cache: *root-save-yarn-cache
      - run:
          name: Run build
          command: yarn build
  deploy:
    <<: *defaults
    steps:
      - checkout:
          path: ~/unmock-docs
      - run:
          name: Deploy master
          command: |
            echo "Not implemented"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #      - build
      #    filters:
      #      branches:
      #        only: master